# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Test

permissions: {}

on:
  pull_request:
    branches:
      - main

jobs:
  yes:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ true }}
      - name: Adding markdown
        run: echo '### Hello world (YES) ! 🚀' >> $GITHUB_STEP_SUMMARY
  no:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ false }}
      - name: Adding markdown
        run: echo '### Hello world (NO) ! 🚀' >> $GITHUB_STEP_SUMMARY